# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeIntegrationExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeIntegrationExample
  pod 'FelgoIOS', :git => 'https://github.com/V-Play/VPlayIOS.git'

end
